DELETE FROM product;
DELETE FROM member;
DELETE FROM cart_item;
DELETE FROM orders;
DELETE FROM order_item;
DELETE FROM coupon;
DELETE FROM discount;

ALTER TABLE product ALTER COLUMN product_id RESTART WITH 1;
ALTER TABLE member ALTER COLUMN member_id RESTART WITH 1;
ALTER TABLE cart_item ALTER COLUMN cart_item_id RESTART WITH 1;
ALTER TABLE orders ALTER COLUMN order_id RESTART WITH 1;
ALTER TABLE order_item ALTER COLUMN order_item_id RESTART WITH 1;
ALTER TABLE coupon ALTER COLUMN coupon_id RESTART WITH 1;
ALTER TABLE discount ALTER COLUMN discount_id RESTART WITH 1;
